# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: aws-aurora-postgres-resources
  description: 'This component is responsible for provisioning Aurora Postgres resources: additional databases, users, permissions, grants, etc'
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-component




